// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdiguO3HcR6Oz36xxs1xGQg4Dt32ivuxU',
    appId: '1:122059133570:web:1991f4a5febf65bccb9a9b',
    messagingSenderId: '122059133570',
    projectId: 'campushub-5e931',
    authDomain: 'campushub-5e931.firebaseapp.com',
    databaseURL: 'https://campushub-5e931-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campushub-5e931.firebasestorage.app',
    measurementId: 'G-9DR2D6Q1HY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdM5KBM5MhPoVA1NhQv2R76WXB55tElos',
    appId: '1:122059133570:android:4c4ca7a79d66ddd6cb9a9b',
    messagingSenderId: '122059133570',
    projectId: 'campushub-5e931',
    databaseURL: 'https://campushub-5e931-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campushub-5e931.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDka_yG-hgAqcmo77QSmDbGFKor02wHdq0',
    appId: '1:122059133570:ios:33d41e2a7e598a28cb9a9b',
    messagingSenderId: '122059133570',
    projectId: 'campushub-5e931',
    databaseURL: 'https://campushub-5e931-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campushub-5e931.firebasestorage.app',
    iosBundleId: 'com.example.campushubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDka_yG-hgAqcmo77QSmDbGFKor02wHdq0',
    appId: '1:122059133570:ios:33d41e2a7e598a28cb9a9b',
    messagingSenderId: '122059133570',
    projectId: 'campushub-5e931',
    databaseURL: 'https://campushub-5e931-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campushub-5e931.firebasestorage.app',
    iosBundleId: 'com.example.campushubApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdiguO3HcR6Oz36xxs1xGQg4Dt32ivuxU',
    appId: '1:122059133570:web:e1aed2ca739a055fcb9a9b',
    messagingSenderId: '122059133570',
    projectId: 'campushub-5e931',
    authDomain: 'campushub-5e931.firebaseapp.com',
    databaseURL: 'https://campushub-5e931-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campushub-5e931.firebasestorage.app',
    measurementId: 'G-CQ4BRKN6Q8',
  );
}
